### PR TITLE
Add download module and command line interface.

### PR DESCRIPTION
**Pull request by cpaulik**

### CODE REVIEW

**Comment by sebhahn** [comment]
@mazweg could you please check if the branch works and all tests succeed? thanks!

**Comment by mazweg** [comment]
I tested it and the only test failing was test_download_SPL3SMP_ftp due to the login on the ftp server without username and password. Not sure if this was possible back then or I am missing something. Maybe @cpaulik can enlighten me.

**Comment by cpaulik** [comment]
This has worked in the past, but it seems that the FTP download was removed completely in the meantime.

**Comment by sebhahn** [comment]
@cpaulik what do you suggest? should we create a "dummy user" or use e.g. a config file?

**Comment by cpaulik** [comment]
If we want to test it with configuration then we can use environment variables in Travis to provide username and password see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings for an example. Implementing this depends on the priority that SMAP has for you, since there would need to be code and documentation changes for these environment variables.

**Comment by sebhahn** [comment]
@mazweg could you please look into the suggestion from @cpaulik

**Comment by mazweg** [comment]
https://nsidc.org/support/faq/what-options-are-available-bulk-downloading-data-https-earthdata-login-enabled
new method with wget, but changing it has not a high priority right now.

**Comment by wpreimes** [comment]
just fyi, I'm going to add support for [smap v.5](https://nsidc.org/data/SPL3SMP/versions/5) data to the package. I'd also check the download routine, that @cpaulik made and include it then in the next PR (if ftp is not working anymore, I remove it together with the test). If we want to still test the download then, we we have to think about how we'd handle it.

**Pull request merged**
